<?php
declare(strict_types=1);
/** @var Template $block */
/** @var BubbleHouseConfigProvider $configProvider */
/** @var SecureHtmlRenderer $secureRenderer */

use BubbleHouse\Integration\Block\Widget\Iframe;
use BubbleHouse\Integration\ViewModel\BubbleHouseConfigProvider;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

$configProvider = $block->getData('config_provider');
?>

<?= $block->getLayout()
    ->createBlock(Iframe::class)
    ->setData([
        'title' => 'Rewards',
        'page' => 'Rewards7',
        'height' => '1700'
    ])
    ->toHtml()
?>

<?php if (!empty($configProvider->getCustomStyles())):?>
<?= $secureRenderer->renderTag('style', [], $configProvider->getCustomStyles(), true) ?>
<?php endif;
