<?php
declare(strict_types=1);
/** @var Template $block */
/** @var BubbleHouseConfigProvider $configProvider */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

use BubbleHouse\Integration\Block\Widget\Iframe;
use BubbleHouse\Integration\ViewModel\BubbleHouseConfigProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;?>

<?= $block->getLayout()
    ->createBlock(Iframe::class)
    ->setData([
        'title' => 'Rewards',
        'page' => 'Rewards7',
        'height' => '1700'
    ])
    ->toHtml();
?>

