<?php
declare(strict_types=1);
/** @var Template $block */
/** @var TokenProvider $tokenProvider */
/** @var Escaper $escaper */

use BubbleHouse\Integration\ViewModel\TokenProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

$tokenProvider = $block->getData('token_provider'); ?>

<?php if ($tokenProvider->isEnabled() && $tokenProvider->isCustomerLoggedIn()) : ?>
    <iframe id="bhpage"
            src="https://app.bubblehouse.com/blocks/v2023061/<?= $escaper->escapeHtmlAttr($tokenProvider->getShopSlug()) ?>/Rewards7?instance=bhpage&auth=<?= $escaper->escapeHtmlAttr($tokenProvider->getCustomerToken()) ?>"
            sandbox="allow-top-navigation allow-scripts allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin"
            allow="clipboard-write"
            style="border: 0; width: 100%; height: 1500px;"></iframe>
<?php else : ?>
<?= $escaper->escapeHtml(__('Enable BubbleHouse or Login')) ?>
<?php endif;
