<?php

declare(strict_types=1);
/** @var Template $block */
/** @var BubbleHouseConfigProvider $configProvider */
/** @var Escaper $escaper */
/** @var SecureHtmlRenderer $secureRenderer */

use BubbleHouse\Integration\ViewModel\BubbleHouseConfigProvider;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Framework\View\Helper\SecureHtmlRenderer;

$configProvider = $block->getData('config_provider');
$nonce = $block->getData('nonce');
$devMode = $configProvider->isDevMode() ? 'true' : 'false';
$nonceOption = $nonce === null ? '' : ', nonce: ' . json_encode(
    $nonce,
    JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT
);
?>

<div id="bubblehouse-checkout-widget"></div>

<?= $secureRenderer->renderTag(
    'script',
    ['type' => 'text/javascript'],
    <<<SCRIPT
        function Bubblehouse_OnLoad_Widget() {
            require(['BubbleHouse_Integration/js/cart_api']);

            window.Bubblehouse.widgets.embed(
                "#bubblehouse-checkout-widget",
                "{$configProvider->getWidgetId()}",
                {
                    slug: "{$configProvider->getShopSlug()}",
                    host: "{$configProvider->getApiHost()}",
                    token: "{$configProvider->getCustomerToken()}"
                },
                { dev: { enabled: {$devMode} }{$nonceOption} },
            )
        }
    SCRIPT,
    false
); ?>

<?= $secureRenderer->renderTag(
    'script',
    ['src' => 'https://' .  $configProvider->getApiHost() . '/static/js/magento-widget.js'],
    '',
    false
); ?>
